### ISSUE TITLE
What checkpoint to use for SGDET?

### ISSUE THREAD

**Issue by wishforgood** [yrcong/NODIS#3]
As the guideline says, models for sgcls and predcls are trained from checkpoints/vgdet/vg-24.tar. Model for sgdet may need to be trained based on the former models, but which one to use? Or maybe model for sgcls should be trained based on model for predcls?

**Comment by wishforgood** [comment]
The sgdet model you provide is named "vgrel-30.tar", does it means that the sgdet model is trained based on sgcls model on epoch 10?

**Comment by yrcong** [comment]
Hi,
i remember the SGDET model is trained based on SGCLS model. The performance is limited by RPN. Our code is based on Motifs code and when training SGDET the assignment function gives a lot of Background-Box. So only a few percentages of pair proposals are meaningful and can "teach" the NODIS.
I am trying to use another assignment method for my next work :-) Hope it will be better.

**Comment by wishforgood** [comment]
OK, thanks for your quick response.

**Comment by wishforgood** [comment]
> Our code is based on Motifs code and when training SGDET the assignment function gives a lot of Background-Box. So only a few percentages of pair proposals are meaningful and can "teach" the NODIS.
> I am trying to use another assignment method for my next work :-) Hope it will be better.

Can a better detector help solve this problem? Or is it simply because of the way ground truth relations are sampled?

**Comment by yrcong** [comment]
A better detector is exactly helpful. We use this pretrained detector (based on VGG16) for fair comparison with other works. A better detector (e.g. FPN) will provide better bboxes and even better feature maps.

**Comment by wishforgood** [comment]
I get it, thanks a lot.
